config/routes.rb
Imecapp::Application.routes.draw do
  get "dashboard/index", :as=>:dashboard

  resources :addresses
  resources :companies

  resources :supporters do
    resources :companies
  end

  resources :providers do
    resources :companies
  end

  devise_for :users

  get "index/index"

  root :to => 'index#index'

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :addressable, :polymorphic=>true

  validates :address, :city, :state, :zipcode, :presence=>true
end

app/models/company.rb
class Company < ActiveRecord::Base
  serialize :accreditations

  has_one :address, :as=>:addressable
  has_many :users

  accepts_nested_attributes_for :address

  validates :name, :tax_id, :uniqueness=>true, :presence=>true
  validates :company_type, :presence=>true, :inclusion => { :in=>%w( provider supporter ) }

  validates_associated :address
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable#, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :first_name, :last_name, :email, :password, :password_confirmation, :remember_me

  has_one :address
  belongs_to :company

  validates :first_name, :last_name, :email, :password, :presence=>true
  validates :password, :confirmation=>true
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

  before_filter :authenticate_user!
  before_filter :load_user

  def new
    @company = Company.new
    @address = @company.build_address
  end

  def create
    @company = Company.new(params[:company])
    @company.company_type = @user.view_type

    if @company.save
      @user.company = @company
      @user.save

      flash[:success] = "Thank you for signing up. Your dashboard is where you will perform all of your actions."
      redirect_to dashboard_path
    else
      render :new
    end
 
  end

  protected

  def load_user
    @user = current_user
  end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
  end
end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  def new
    @user = User.new
    #@user.view_type = "provider"
  end

  def create
    @user = User.new(params[:user])
    @user.view_type = "provider"

    if @user.save
      sign_in(@user)
      flash[:success] = "Thank you for signing up."
      redirect_to new_company_path
    else
      render :new
    end
  end

end

app/controllers/supporters_controller.rb
class SupportersController < ApplicationController
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    @user.view_type = "supporter"

    if @user.save
      sign_in(@user)
      flash[:success] = "Thank you for signing up."
      redirect_to new_company_path
    else
      render :new
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :load_company

  def new
    @user = @company.users.build(:view_type=>@company.company_type)
  end

  def create
    @user = @company.users.build(params[:user])

    if @user.save
      flash[:success] = "You have completed your registration. Thank You!"
      redirect_to  dashboard_path
    else
      render :new
    end
  end

  protected

  def load_company
    if params[:provider_id]
      @company = Company.find(params[:provider_id])
    elsif params[:supporter_id]
      @company = Company.find(params[:supporter_id])
    elsif params[:company_id]
      @company = Company.find(params[:company_id])
    else
      flash[:notice] = "Please add new users to a company. If your company is already registered an administrator of your company account can add you to the company."
      redirect_to  root_path and return false
    end 
  end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/helpers/supporters_helper.rb
module SupportersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/addresses/_form.html.erb
<div class="control-group">
  <%= f.label :address, "Address", :class=>"control-label" %>
  <div class="controls">
    <%= f.text_field :address %>
  </div>
</div>
<div class="control-group">
  <%= f.label :address2, "Address Suite/Room", :class=>"control-label" %>
  <div class="controls">
    <%= f.text_field :address2 %>
  </div>
</div>
<div class="control-group">
  <%= f.label :city, "City", :class=>"control-label" %>
  <div class="controls">
    <%= f.text_field :city %>
  </div>
</div>
<div class="control-group">
  <%= f.label :state, "State", :class=>"control-label" %>
  <div class="controls">
    <%= f.text_field :state %>
  </div>
</div>
<div class="control-group">
  <%= f.label :zipcode, "Zipcode", :class=>"control-label" %>
  <div class="controls">
    <%= f.text_field :zipcode %>
  </div>
</div>

app/views/companies/_form.html.erb
  <div class="control-group">
    <%= f.label :name, "Legal Name", :class=>"control-label" %>
    <div class="controls">
      <%= f.text_field :name %>
    </div>
  </div>
  <%= f.fields_for :address do |a| %>
    <%= render "addresses/form",{:f=>a} %>
  <% end %>
  <div class="control-group">
    <%= f.label :tax_id, "Tax ID", :class=>"control-label" %>
    <div class="controls">
      <%= f.text_field :tax_id %>
    </div>
  </div> 
  <div class="control-group">
    <%= f.label :accreditations, "Accreditations", :class=>"control-label" %>
    <div class="controls">
      <%= f.select :accreditations,['ACCME','ACNP','CPNP','ETC'], {},{:multiple=>true} %>
    </div>
  </div> 
   <div class="control-group">
    <%= f.label :is_501c3, "501(c3)", :class=>"control-label" %>
    <div class="controls">
      <%= f.radio_button :is_501c3, "Yes" %> <%= f.label :is_501c3, "Yes" %> <%= f.radio_button :is_501c3,"No" %> <%= f.label :is_501c3, "No" %>
    </div>
  </div> 
  <div class="form-actions">
  <%= f.submit "Save Company and Continue",:class=>"btn btn-primary" %> 
  </div>

app/views/companies/new.html.erb
<h1>Add Company <small><%= @user.view_type.capitalize %></small></h1>

<%= form_for @company, :html=>{:class=>"form-horizontal"} do |f| %>
  <%= render "form", {:f=>f} %>
<% end %>

app/views/dashboard/index.html.erb
<h1>Dashboard#index</h1>
<p>Find me in app/views/dashboard/index.html.erb</p>

app/views/index/index.html.erb
<h1 class="title">Improved Patient Care Through Improved CME Process</h1>
<div class="row-fluid">
  <div class="span4">
    <div class="hero-unit">
      <h2>Standardize</h2>
    </div>
  </div>
  <div class="span4">
    <div class="hero-unit">
      <h2>Transparent</h2>
    </div>
  </div>
  <div class="span4">
    <div class="hero-unit">
      <h2>Communicate</h2>
    </div>
  </div>
</div>
<div class="row-fluid">
  <div class="span6" style="margin: 0 auto;">
    <%= link_to "Provider Signup", new_provider_path, :class=>"btn btn-large btn-primary" %>
    <%= link_to "Supporter Signup", new_supporter_path, :class=>"btn btn-large btn-inverse" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>IMEC</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- Le styles -->
  <%= stylesheet_link_tag 'application' %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

  <!-- Le fav and touch icons -->
  <link rel="shortcut icon" href="../assets/ico/favicon.ico">
  <link rel="apple-touch-icon-precomposed" sizes="114x114" href="../assets/ico/apple-touch-icon-114-precomposed.png">
  <link rel="apple-touch-icon-precomposed" sizes="72x72" href="../assets/ico/apple-touch-icon-72-precomposed.png">
  <link rel="apple-touch-icon-precomposed" href="../assets/ico/apple-touch-icon-57-precomposed.png">
</head>

<body>

  <div class="navbar">
    <div class="navbar-inner">
      <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <%= link_to "IMEC", root_path, :class=>"brand" %>
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to "Login", new_user_session_path %></li>
        </ul>
      </div><!--/.nav-collapse -->
      </div>
    </div>
  </div>
  

  <div class="container">
  <%= content_for?(:content) ? yield(:content) : yield %>
  </div> <!-- /main -->

<%= javascript_include_tag 'application' %>
</body>
</html>

app/views/providers/new.html.erb
<h1>Sign Up <small>New Provider</small></h1>
<%= form_for @user, :url=>providers_path, :html=>{:class=>"form-horizontal"} do |f| %>
  <%= f.error_messages %>
  <%= render "users/form",{:f=>f} %>
<% end %>

app/views/supporters/new.html.erb
<h1>Sign Up <small>New Supporter</small></h1>
<%= form_for @user, :url=>supporters_path, :html=>{:class=>"form-horizontal"} do |f| %>
  <%= f.error_messages %>
  <%= render "users/form",{:f=>f} %>
<% end %>

app/views/users/_form.html.erb
<div class="control-group">
  <%= f.label :first_name, :class=>"control-label" %>
  <div class="controls">
    <%= f.text_field :first_name %>
  </div>
</div>
<div class="control-group">
  <%= f.label :last_name, :class=>"control-label" %>
  <div class="controls">
    <%= f.text_field :last_name %>
  </div>
</div>
<div class="control-group">
  <%= f.label :email, :class=>"control-label" %>
  <div class="controls">
    <%= f.text_field :email %>
  </div>
</div>
<div class="control-group">
  <%= f.label :password, :class=>"control-label" %>
  <div class="controls">
    <%= f.text_field :password %>
  </div>
</div>
<div class="control-group">
  <%= f.label :password_confirmation, :class=>"control-label" %>
  <div class="controls">
    <%= f.text_field :password_confirmation %>
  </div>
</div>
<div class="form-actions">
  <%= f.submit "Save and Continue", :class=>"btn btn-primary" %>
</div>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up - User</h1>
<%= form_for @user, :url=>users_path(@user) do |f| %>
  <%= render "form", {:f=>f} %>
<% end %>